# Generated by Django 5.2.6 on 2025-09-14 17:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mana_cost', models.CharField(blank=True, max_length=20, null=True)),
                ('type_line', models.CharField(choices=[('Land', 'Land'), ('Creature', 'Creature'), ('Enchantment', 'Enchantment'), ('Artifact', 'Artifact'), ('Planeswalker', 'Planeswalker'), ('Sorcery', 'Sorcery'), ('Instant', 'Instant'), ('Battle', 'Battle'), ('Tribal', 'Tribal'), ('Conspiracy', 'Conspiracy'), ('Plane', 'Plane'), ('Scheme', 'Scheme'), ('Vanguard', 'Vanguard')], max_length=100)),
                ('primary_type', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_types', models.CharField(blank=True, max_length=100, null=True)),
                ('box_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardInDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_links', to='cards.card')),
            ],
            options={
                'verbose_name': 'Card in Deck',
                'verbose_name_plural': 'Cards in Deck',
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('format', models.CharField(choices=[('Standard', 'Standard'), ('Modern', 'Modern'), ('Legacy', 'Legacy'), ('Vintage', 'Vintage'), ('Jumpstart', 'Jumpstart'), ('Commander', 'Commander'), ('Premondern', 'Premondern'), ('Pioneer', 'Pioneer'), ('Historic', 'Historic'), ('Brawl', 'Brawl'), ('Pauper', 'Pauper'), ('Frontier', 'Frontier'), ('Old School', 'Old School'), ('Singleton', 'Singleton'), ('Two-Headed Giant', 'Two-Headed Giant'), ('Oathbreaker', 'Oathbreaker'), ('Momir Basic', 'Momir Basic'), ('Peasant', 'Peasant'), ('Canadian Highlander', 'Canadian Highlander'), ('Tiny Leaders', 'Tiny Leaders'), ('Epic', 'Epic'), ('Conspiracy', 'Conspiracy'), ('Planechase', 'Planechase'), ('Archenemy', 'Archenemy'), ('Vanguard', 'Vanguard'), ('Other', 'Other')], default='Jumpstart', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cards', models.ManyToManyField(blank=True, related_name='decks', through='cards.CardInDeck', to='cards.card')),
            ],
        ),
        migrations.AddField(
            model_name='cardindeck',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_links', to='cards.deck'),
        ),
        migrations.AlterUniqueTogether(
            name='cardindeck',
            unique_together={('deck', 'card')},
        ),
    ]
