# Generated by Django 5.2.6 on 2025-09-13 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Standard', 'Standard'), ('Modern', 'Modern'), ('Legacy', 'Legacy'), ('Vintage', 'Vintage'), ('Jumpstart', 'Jumpstart'), ('Commander', 'Commander'), ('Premondern', 'Premondern'), ('Pioneer', 'Pioneer'), ('Historic', 'Historic'), ('Brawl', 'Brawl'), ('Pauper', 'Pauper'), ('Frontier', 'Frontier'), ('Old School', 'Old School'), ('Singleton', 'Singleton'), ('Two-Headed Giant', 'Two-Headed Giant'), ('Oathbreaker', 'Oathbreaker'), ('Momir Basic', 'Momir Basic'), ('Peasant', 'Peasant'), ('Canadian Highlander', 'Canadian Highlander'), ('Tiny Leaders', 'Tiny Leaders'), ('Epic', 'Epic'), ('Conspiracy', 'Conspiracy'), ('Planechase', 'Planechase'), ('Archenemy', 'Archenemy'), ('Vanguard', 'Vanguard'), ('Other', 'Other')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Decks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cards', models.ManyToManyField(related_name='cards_in_deck', to='cards.card')),
                ('format', models.ForeignKey(default='Jumpstart', on_delete=django.db.models.deletion.CASCADE, to='cards.format')),
            ],
        ),
    ]
