# Generated by Django 5.2.6 on 2025-09-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='secondary_types',
            new_name='subtypes',
        ),
        migrations.RemoveField(
            model_name='card',
            name='primary_type',
        ),
        migrations.RemoveField(
            model_name='card',
            name='type_line',
        ),
        migrations.AddField(
            model_name='card',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='set',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
